[package]
name = "geo302"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "3.1", features = ["derive"] }
maxminddb = { version = "0.22", default_features = false, features = ["unsafe-str-decode"] }
reqwest = "0.11"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
smallvec = { version = "1.8", default_features = false, features = ["union"]}
thiserror = "1.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
url = "2.2"
warp = { version = "0.3.2", default_features = false }