host = "0.0.0.0:8000"
ip_headers = ["x-real-ip", "x-forwarded-for"]
ip_headers_recursive = true
healthckeck_interval = 5
response_headers = { Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET" }
log_level = "info"
threads = 2

[geoip]
#type = "maxminddb"
#path = "./GeoLite2-Country/GeoLite2-Country.mmdb"
type = "ripe-geo"
path = "./ripe-geo/continents"
overlaps = "skip"
autoupdate = { url = "https://github.com/cbuijs/ripe-geo/archive/refs/heads/master.tar.gz", interval = 86400 }

[mirrors.sai]
upstream = "https://sai.fits.ztf.snad.space/"
healthcheck = "https://sai.fits.ztf.snad.space/products/"

[mirrors.uci]
upstream = "https://uci.fits.ztf.snad.space/"
healthcheck = "https://uci.fits.ztf.snad.space/products/"

[continents]
Africa = ["sai", "uci"]
Asia = ["sai", "uci"]
Europe = ["sai", "uci"]
NorthAmerica = ["uci", "sai"]
Oceania = ["uci", "sai"]
SouthAmerica = ["uci", "sai"]
Antarctica = ["uci", "sai"]
default = ["sai", "uci"]
