name: Test

on: 
  push:
  pull_request:
  schedule:
    - cron: '17 1 1 * *'

jobs:
  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cargo fmt -- --check
  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cargo clippy --all-targets -- -D warnings
  cargo-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - run: cargo test
  msrv-cargo-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get minimum supported Rust version
      run: echo "::set-output name=msrv::$(grep '^rust-version = ' Cargo.toml | grep -o '[0-9.]\+')"
      id: get_msrv
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ steps.get_msrv.outputs.msrv }}
    - run: cargo +${{ steps.get_msrv.outputs.msrv }} build --all-targets
  audit-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: cargo install cargo-audit
      - run: cargo audit

